### ISSUE TITLE
0 으로 나누면 비정상 종료한다.

### ISSUE THREAD

**Issue by brixxt27** [brixxt27/cpp_module_09#8]

**Comment by brixxt27** [comment]
```
(lldb) c
Process 5585 resuming
Process 5585 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0)
    frame #0: 0x00000001000056c9 RPN`RPN::executeRPN(this=0x00007ffeefbff3e0, exp="1 0 /") at RPN.cpp:74:25
   71                           else
   72                           {
   73                                   try{
-> 74                                   _my_stack.push(num1 / num2);
   75                                   }
   76                                   catch (std::exception& e){
   77                                           std::cout << "Hi" << std::endl;
Target 0: (RPN) stopped.
(lldb) exit
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] Y
jayoon@c1r2s7 ex01 % exitY
zsh: command not found: exitY
jayoon@c1r2s7 ex01 % ls
Makefile        RPN             RPN.cpp         RPN.hpp         RPN.o           main.cpp        main.o
jayoon@c1r2s7 ex01 % ./RPN "1 0 /"
AddressSanitizer:DEADLYSIGNAL
=================================================================
==5724==ERROR: AddressSanitizer: FPE on unknown address 0x00010a6eb6c9 (pc 0x00010a6eb6c9 bp 0x7ffee5519490 sp 0x7ffee5519180 T0)
    #0 0x10a6eb6c9 in RPN::executeRPN(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) RPN.cpp:74
    #1 0x10a6e7b29 in main main.cpp:67
    #2 0x7fff6a7b5cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==5724==Register values:
rax = 0x0000000000000001  rbx = 0x00007ffee5519260  rcx = 0x0000000000000001  rdx = 0x0000000000000000  
rdi = 0x00007ffee55191a0  rsi = 0x0000100000000000  rbp = 0x00007ffee5519490  rsp = 0x00007ffee5519180  
 r8 = 0x60c234bd65670000   r9 = 0x60c234bd656700cd  r10 = 0x000000000000000a  r11 = 0xffffffffffffff20  
r12 = 0x00007ffee55194c0  r13 = 0x00007ffee5519520  r14 = 0x00007ffee5519240  r15 = 0x00001fffdcaa3230  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE RPN.cpp:74 in RPN::executeRPN(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
==5724==ABORTING
zsh: abort      ./RPN "1 0 /"
jayoon@c1r2s7 ex01 % make re
make fclean
rm -rf main.o RPN.o
rm -rf RPN
make all
c++ --std=c++98 -Wall -Wextra -Werror -I ./ -c main.cpp -o main.o
c++ --std=c++98 -Wall -Wextra -Werror -I ./ -c RPN.cpp -o RPN.o
c++ --std=c++98 -Wall -Wextra -Werror -I ./ main.o RPN.o -o RPN
jayoon@c1r2s7 ex01 % ./RPN "1 0 /"
zsh: floating point exception  ./RPN "1 0 /"
```

**Comment by brixxt27** [comment]
이를 / 일 때 num2 가 0이 되면 에러로 처리했다.
